name: Docker Images

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build API image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: infra/docker/Dockerfile.api
          target: runner
          push: false
          tags: aiseo/api:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build Web image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: infra/docker/Dockerfile.web
          target: runner
          push: false
          tags: aiseo/web:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build Worker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: infra/docker/Dockerfile.worker
          target: runner
          push: false
          tags: aiseo/worker:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
